class Routine:
    """Handles the skincare products generated by the system"""

    def __init__(self, cleanser, treatmentAM, moisturizerAM, sunscreen,
                 treatmentPM, moisturizerPM):
        self.cleanser = cleanser
        self.treatmentAM = treatmentAM
        self.moisturizerAM = moisturizerAM
        self.sunscreen = sunscreen
        self.treatmentPM = treatmentPM
        self.moisturizerPM = moisturizerPM

